version: 2

sources:
  - name: uber_snowflake
    database: UBER_PROJECT
    schema: STAGING  # This is where RAW_UBER_TRIPS lives
    tables:
      - name: RAW_UBER_TRIPS
        description: "Raw Uber trips data"